---
jinja2_transforms:
  - name: "device_arista"
    description: "Template to generate startup configuration for Arista devices"
    query: "device_info"
    template_path: "templates/device_arista_config.tpl.j2"

  - name: "clab_topology"
    query: "topology_info"
    template_path: "topology/clab_topology.j2"

  - name: "suzieq_inventory"
    query: "devices"
    template_path: "suzieq/inventory.j2"

artifact_definitions:
  - name: "Startup Config for Arista devices"
    artifact_name: "startup-config"
    parameters:
      device: "name__value"
    content_type: "text/plain"
    targets: "arista"
    transformation: "device_arista"

  - name: "Containerlab Topology"
    artifact_name: "containerlab-topology"
    parameters:
      topology_name: "name__value"
    content_type: "text/plain"
    targets: "arista"
    transformation: "clab_topology"

  - name: "SuzieQ Inventory"
    artifact_name: "suzieq-inventory"
    parameters:
      device: "name__value"
    content_type: "text/plain"
    targets: "arista"
    transformation: "suzieq_inventory"

queries:
  - name: "topology_info"
    file_path: "topology/topology_info.gql"

  - name: "device_info"
    file_path: "templates/device_info.gql"

  - name: "devices"
    file_path: "suzieq/devices.gql"