[project]
name = "infrahub-ac3-schema"
version = "0.2.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11, < 3.13"
dependencies = [
    "infrahub-sdk[all]~=1.12.0",
    "invoke>=2.2.0",
    "paramiko>=3.5.1",
    "requests>=2.32.3",
]
